import {
    Heart, HeartPulse, Building2, Users, UserCircle, Activity, Baby, Car, Home, Plane, UserX, Gem, UserCheck,
    Briefcase, Network, Scale, Ship, Zap, Database, Search, Calculator, Bot, FileText, Shield, BarChart3
} from 'lucide-react'

export const insuranceCategories = [
    { href: '/insurance/life', icon: Heart, title: 'Life Insurance', desc: 'Term, Whole Life, ULIPs', color: 'from-red-500 to-pink-600' },
    { href: '/insurance/term-life', icon: HeartPulse, title: 'Term Life', desc: 'Pure Protection, High Cover', color: 'from-blue-500 to-cyan-600' },
    { href: '/insurance/health', icon: Building2, title: 'Health Insurance', desc: 'Individual, Family, Critical Illness', color: 'from-emerald-500 to-teal-600' },
    { href: '/insurance/family-floater', icon: Users, title: 'Family Floater', desc: 'One Policy, Entire Family', color: 'from-fuchsia-500 to-pink-600' },
    { href: '/insurance/senior-citizen', icon: UserCircle, title: 'Senior Citizen', desc: 'Care for your Parents', color: 'from-teal-500 to-emerald-600' },
    { href: '/insurance/critical-illness', icon: Activity, title: 'Critical Illness', desc: 'Life-Changing Illness Cover', color: 'from-rose-500 to-red-600' },
    { href: '/insurance/maternity', icon: Baby, title: 'Maternity Insurance', desc: 'Welcoming New Life Safely', color: 'from-pink-500 to-rose-600' },
    { href: '/insurance/motor', icon: Car, title: 'Motor Insurance', desc: 'Car, Bike, Comprehensive', color: 'from-blue-500 to-indigo-600' },
    { href: '/insurance/home', icon: Home, title: 'Home Insurance', desc: 'Building, Contents, Fire', color: 'from-amber-500 to-orange-600' },
    { href: '/insurance/travel', icon: Plane, title: 'Travel Insurance', desc: 'Domestic, International', color: 'from-purple-500 to-violet-600' },
    { href: '/insurance/disability', icon: UserX, title: 'Disability Cover', desc: 'Income Protection for Injuries', color: 'from-indigo-500 to-purple-600' },
    { href: '/insurance/specialized', icon: Gem, title: 'Specialized', desc: 'Pet, Wedding, Gadget', color: 'from-cyan-500 to-blue-600' },
    { href: '/insurance/personal-accident', icon: UserCheck, title: 'Personal Accident', desc: 'Disability, Death, Medical', color: 'from-rose-500 to-red-600' },
]

export const businessCategories = [
    { href: '/insurance/business', icon: Briefcase, title: 'Commercial Package', desc: 'SME, Corporate Property, Interruption', color: 'from-slate-600 to-gray-800' },
    { href: '/insurance/cyber', icon: Network, title: 'Cyber Security Cover', desc: 'Data Breach, Ransomware, Liability', color: 'from-teal-500 to-emerald-600' },
    { href: '/insurance/liability', icon: Scale, title: 'Liability Insurance', desc: 'Public, Product, D&O, Professional', color: 'from-amber-500 to-orange-600' },
    { href: '/insurance/marine', icon: Ship, title: 'Marine & Aviation', desc: 'Cargo, Hull, Freight Liability', color: 'from-blue-500 to-cyan-600' },
    { href: '/insurance/ev', icon: Zap, title: 'EV & Emerging Tech', desc: 'Electric Vehicles, AI, Parametric', color: 'from-fuchsia-500 to-purple-600' },
    { href: '/insurance/directory', icon: Database, title: 'Insurance Directory', desc: 'Verified Directory of Indian Insurers', color: 'from-indigo-600 to-blue-700' },
]

export const tools = [
    {
        href: '/tools/ai-scanner',
        icon: Bot,
        title: 'Policy AI Auditor',
        desc: 'Upload any policy PDF. Our AI scans thousands of words to detect "Hidden Exclusions" and Red Flags.',
        badge: 'AI Powered',
        stat: 'Audit',
        statLabel: 'Instant Scan',
        color: 'from-rose-500 to-red-600',
        gradient: 'from-rose-500/20 via-red-500/10 to-transparent',
    },
    {
        href: '/tools/hlv-calculator',
        icon: Calculator,
        title: 'HLV Calculator',
        desc: 'Calculate exactly how much Life Cover you need based on income, liabilities, and inflation.',
        badge: 'Free',
        stat: 'Smart',
        statLabel: 'HLV Result',
        color: 'from-emerald-500 to-green-600',
        gradient: 'from-emerald-500/20 via-green-500/10 to-transparent',
    },
    {
        href: '/tools/claim-search',
        icon: Search,
        title: 'Claim Case Search',
        desc: 'Search real-life insurance claim cases. Learn what got approved, rejected, and why.',
        badge: 'New',
        stat: '30+',
        statLabel: 'Case Laws',
        color: 'from-blue-500 to-indigo-600',
        gradient: 'from-blue-500/20 via-indigo-500/10 to-transparent',
    },
    {
        href: '/tools/room-rent',
        icon: Home,
        title: 'Room Rent Mapper',
        desc: 'Impact of Room Rent Capping on your surgical claims. Visualize your potential out-of-pocket loss.',
        badge: 'Critical',
        stat: 'Mapper',
        statLabel: 'Loss Check',
        color: 'from-amber-400 to-orange-500',
        gradient: 'from-amber-400/20 via-orange-500/10 to-transparent',
    },
    {
        href: '/tools/tax-benefit',
        icon: Zap,
        title: 'Tax Benefit Check',
        desc: 'Compare Old vs New Tax Regimes. See how insurance premiums (80C/80D) save you money.',
        badge: 'FY 24-25',
        stat: 'Compare',
        statLabel: 'Tax Logic',
        color: 'from-indigo-500 to-purple-600',
        gradient: 'from-indigo-500/20 via-purple-500/10 to-transparent',
    },
    {
        href: '/tools/hidden-facts',
        icon: FileText,
        title: 'Hidden Facts',
        desc: '150+ expert-curated facts about insurance traps that companies don\'t want you to know.',
        badge: 'Expert',
        stat: '150+',
        statLabel: 'Exposed',
        color: 'from-slate-600 to-gray-800',
        gradient: 'from-slate-600/20 via-gray-800/10 to-transparent',
    }
]

export const stats = [
    { value: 150, label: 'Hidden Facts', icon: Search, suffix: '+' },
    { value: 13, label: 'Insurance Types', icon: Shield, suffix: '' },
    { value: 6, label: 'Free Tools', icon: BarChart3, suffix: '' },
    { value: 30, label: 'Claim Cases', icon: FileText, suffix: '+' },
]

export const partnerLogos = [
    { name: "LIC", url: "/Logos/life-insurance-corporation-logo-png_seeklogo-477287.png", w: 160, h: 60 },
    { name: "HDFC Life", url: "/Logos/HDFC-Life-Logo.png", w: 120, h: 40 },
    { name: "Aditya Birla", url: "/Logos/Aditya Birla Insurace.png", w: 160, h: 60 },
    { name: "ICICI Prudential", url: "/Logos/icici-prudential-life-insurance-logo-png_seeklogo-307031.png", w: 160, h: 60 },
    { name: "SBI Life", url: "/Logos/sbi-life-insurance-logo-png_seeklogo-123116.png", w: 160, h: 60 },
    { name: "Kotak Life", url: "/Logos/kotak-life-insurance-logo-png_seeklogo-212711.png", w: 160, h: 60 },
    { name: "Tata AIA", url: "/Logos/tata-aia-life-insurance-seeklogo.png", w: 160, h: 60 },
    { name: "Bajaj Allianz", url: "/Logos/bajaj-allianz-life-insurance-logo-png_seeklogo-307030.png", w: 160, h: 60 },
    { name: "Max Life", url: "/Logos/axis-max-life-insurance-logo-png_seeklogo-643158.png", w: 160, h: 60 },
    { name: "Star Health", url: "/Logos/star-health-insurance-logo-png_seeklogo-303863.png", w: 160, h: 60 },
    { name: "Care Health", url: "/Logos/Care_health_insurance_logo.png", w: 160, h: 60 },
    { name: "Digit Insurance", url: "/Logos/digit-insurance-logo-png_seeklogo-465810.png", w: 160, h: 60 },
    { name: "Acko", url: "/Logos/Acko_General_Insurance_logo.svg.png", w: 160, h: 60 },
    { name: "IndusInd Nippon Life", url: "/Logos/Reliance_Life_Insurance_Logo.png", w: 160, h: 60 },
    { name: "Reliance General", url: "/Logos/reliance-general-insurance-logo-png_seeklogo-503447.png", w: 160, h: 60 },
    { name: "IndiaFirst Life", url: "/Logos/ifli-logo-new.png", w: 160, h: 60 },
    { name: "HDFC Ergo", url: "/Logos/HDFC-Ergo-Logo.png", w: 160, h: 60 },
    { name: "Nippon Life India", url: "/Logos/nippon-life-insurance-logo-png_seeklogo-99705.png", w: 120, h: 40 },
    { name: "Ageas Federal", url: "/Logos/AgeasFederal-_Logo_Color.png", w: 160, h: 60 },
    { name: "Bharti AXA", url: "/Logos/BhartiAXALifeInsurance.png", w: 160, h: 60 },
    { name: "Generali Central", url: "/Logos/Future Generali insurance.png", w: 160, h: 60 },
    { name: "IFFCO Tokio", url: "/Logos/IFFCO_TOKIO_Logo.png", w: 160, h: 60 },
    { name: "National Insurance", url: "/Logos/National_Insurance_Company.png", w: 160, h: 60 },
    { name: "Oriental Insurance", url: "/Logos/The_Oriental_Insurance_Company_Logo.png", w: 160, h: 60 },
    { name: "United India", url: "/Logos/United_India_Insurance.png", w: 120, h: 40 },
    { name: "Aviva", url: "/Logos/avivi.png", w: 160, h: 60 },
    { name: "Edelweiss", url: "/Logos/edelweisslogo.png", w: 160, h: 60 },
    { name: "Manipal Cigna", url: "/Logos/hi-logo-Manipal.png", w: 200, h: 60 },
    { name: "MetLife", url: "/Logos/met-life-india-logo-png_seeklogo-91366.png", w: 160, h: 60 },
    { name: "Star Union Dai-ichi", url: "/Logos/Star unini dai.png", w: 160, h: 60 },
    { name: "Niva Bupa", url: "/Logos/bupa Insurance.png", w: 160, h: 60 },
    { name: "ICICI Lombard", url: "/Logos/ICICI-Lombard.png", w: 160, h: 60 },
    { name: "New India Assurance", url: "/Logos/New India Assurance.png", w: 160, h: 60 },
    { name: "Cholamandalam MS", url: "/Logos/Cholamandalam MS.png", w: 160, h: 60 },
    { name: "Kotak General", url: "/Logos/Kotak General Insurance.png", w: 160, h: 60 },
]
